// scripts/codegen/lib/contract.ts
// API contract for the TSX component generator.
// Mirrors the Python generator's GenerationRequest / GenerationResult pattern.

export type Provider = "auto" | "ollama" | "gemini" | "anthropic" | "groq"

export type FailureReason =
  | "max_attempts_reached"
  | "llm_unavailable"
  | "static_check_failed"
  | "registry_conflict"
  | "internal_error"

export interface AttemptDetail {
  attempt: number
  error: string
  fixApplied: string
}

// ── Input ────────────────────────────────────────────────────────────────────

export interface ComponentRequest {
  toolId: string          // kebab-case: "japanese-word-count" → URL + file name
  displayName: string     // "Japanese Word Counter"
  description: string     // SEO description, max 160 chars
  features: string[]      // Required features — LLM MUST implement every one
  category?: string       // Auto-inferred by LLM if omitted
  tags?: string[]         // Auto-generated by LLM if omitted
  maxAttempts?: number    // default 3
  provider?: Provider     // default "auto"
  outputDir?: string      // default "./output"
  projectDir?: string     // if set, auto-copies to {projectDir}/components/tools/
                          // and appends registry entries
}

// ── Output ───────────────────────────────────────────────────────────────────

export interface ComponentResult {
  success: boolean
  attemptsUsed: number
  elapsedMs: number
  // success = true
  componentPath?: string    // Absolute path to the generated .tsx file
  registryEntry?: string    // Snippet to append to data/tools.ts
  registryLine?: string     // Single line to append to lib/toolRegistry.ts
  reviewPath?: string       // Absolute path to REVIEW.md
  providerUsed?: string
  // success = false
  failureReason?: FailureReason
  failureMessage?: string
  attemptLog?: AttemptDetail[]
}
